/**
 * Per-interview persona/session config for the Anam avatar.
 *
 * The InterviewOST app already owns the conversational brain (Mastra
 * `interviewerAgent` + rubric + project context, served via /api/chat). We
 * therefore run Anam in **client-driven LLM mode** (`llmId =
 * "CUSTOMER_CLIENT_V1"`): Anam handles only STT, TTS, video, and lip-sync.
 * It does NOT call an LLM. Our client listens for the user transcript,
 * POSTs it to /api/chat, and pushes the response back into the avatar via
 * `anamClient.talk(text)`. No double-brain, no script duplication.
 *
 * Docs: https://anam.ai/docs/personas/llms/custom-llms
 */

// Anam's reserved llmId that tells the platform "the client will provide
// responses via talk()/createTalkMessageStream()."
export const ANAM_CUSTOMER_CLIENT_LLM_ID = "CUSTOMER_CLIENT_V1";

// Default avatar is a custom avatar managed in the project's Anam Lab
// account. To change it: pick another avatar in lab.anam.ai, copy its UUID,
// and paste it here. Voice still defaults to "Liv" from Anam's public gallery.
const DEFAULT_AVATAR_ID = "ee9cc649-dab9-41e5-87fa-1a4048527dcf"; // custom
const DEFAULT_VOICE_ID = "4bdb224b-0342-4986-9831-69a1f059103d"; // "Liv" — warm female

export interface BuildPersonaConfigOptions {
  /** Display name for the persona. Falls back to "Interviewer". */
  personaName?: string;
  /** Anam avatar UUID. Falls back to the project's default avatar. */
  avatarId?: string;
  /** Anam voice UUID. Falls back to Liv. */
  voiceId?: string;
}

export interface AnamPersonaConfig {
  name: string;
  avatarId: string;
  voiceId: string;
  llmId: string;
  systemPrompt: string;
}

export function buildPersonaConfig(opts: BuildPersonaConfigOptions = {}): AnamPersonaConfig {
  return {
    name: opts.personaName ?? "Interviewer",
    avatarId: opts.avatarId ?? DEFAULT_AVATAR_ID,
    voiceId: opts.voiceId ?? DEFAULT_VOICE_ID,
    llmId: ANAM_CUSTOMER_CLIENT_LLM_ID,
    // Required-non-empty by the API but ignored in client-driven mode.
    systemPrompt: "The client provides all responses via talk().",
  };
}

/**
 * Session-level options. We disable Anam's auto-greeting because the opening
 * line is generated by our Interviewer agent on the very first /api/chat call
 * (isStart: true) and spoken via talk(). Barge-in (interruption) stays on.
 */
export const SESSION_OPTIONS = {
  skipGreeting: true,
  uninterruptibleGreeting: false,
} as const;
