"use client";

/**
 * VirtualInterviewer — photoreal Anam avatar that conducts the interview.
 *
 * Anam runs in client-driven LLM mode (see avatarConfig.ts): it owns STT,
 * TTS, video, and lip-sync. The InterviewOST app owns the brain via
 * /api/chat (Mastra interviewerAgent + rubric + Supabase persistence).
 *
 * Turn loop:
 *   1. Avatar streams to <video>. On VIDEO_PLAY_STARTED we fire one
 *      /api/chat with isStart:true → speak the opening line.
 *   2. User speaks. Anam transcribes and updates MESSAGE_HISTORY_UPDATED
 *      with a new user message. We POST it to /api/chat → speak the reply.
 *   3. After each turn we check if the interview row flipped to status
 *      "completed" (the existing /api/chat does that server-side when the
 *      Interviewer agent emits [INTERVIEW_COMPLETE]) and end the session.
 *
 * Typed input: clicking the keyboard icon opens a single-line input. The
 * typed text is sent directly to /api/chat (we deliberately don't route
 * through anamClient.sendUserMessage because in client-driven mode that
 * round-trips through Anam unnecessarily).
 */

import { useCallback, useEffect, useRef, useState } from "react";
import {
  createClient,
  AnamEvent,
  MessageRole,
  type AnamClient,
  type Message,
  type MessageStreamEvent,
} from "@anam-ai/js-sdk";
import { Keyboard, Mic, Send, X } from "lucide-react";
import { createClient as createSupabaseBrowserClient } from "@/lib/supabase/client";
import { buildPersonaConfig, SESSION_OPTIONS } from "./avatarConfig";
import "./VirtualInterviewer.css";

type Status = "idle" | "connecting" | "listening" | "speaking" | "thinking" | "error";

interface VirtualInterviewerProps {
  interviewId: string;
  token: string;
  participantName: string | null;
  /**
   * Opening line already generated by the Interviewer agent during the
   * name-submission step (existing flow in /i/[token]/page.tsx). The avatar
   * speaks it as its first turn rather than calling /api/chat again, which
   * would duplicate the opening message in the messages table.
   */
  openingMessage: string;
  /** Optional persona overrides — wire to project.voice_id etc. later. */
  personaName?: string;
  voiceId?: string;
  /** Called once when the interview transitions to "completed". */
  onComplete: () => void;
}

const VIDEO_ELEMENT_ID = "anam-avatar-video";

export default function VirtualInterviewer({
  interviewId,
  token,
  participantName,
  openingMessage,
  personaName,
  voiceId,
  onComplete,
}: VirtualInterviewerProps) {
  const [status, setStatus] = useState<Status>("idle");
  const [userCaption, setUserCaption] = useState("");
  const [personaCaption, setPersonaCaption] = useState("");
  const [typingOpen, setTypingOpen] = useState(false);
  const [draft, setDraft] = useState("");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [started, setStarted] = useState(false);

  const clientRef = useRef<AnamClient | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const turnInFlightRef = useRef(false);
  const lastUserMessageIdRef = useRef<string | null>(null);
  const completedRef = useRef(false);

  const supabase = createSupabaseBrowserClient();

  /* ------------------------------------------------------------------ */
  /* Brain calls (POST /api/chat).                                       */
  /* ------------------------------------------------------------------ */
  const callBrain = useCallback(
    async (message: string) => {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          interviewId,
          token,
          participantName: participantName ?? undefined,
          message,
        }),
      });
      if (!res.ok) {
        throw new Error(`Brain returned ${res.status}: ${await res.text()}`);
      }
      return await res.text();
    },
    [interviewId, token, participantName],
  );

  const checkCompletion = useCallback(async () => {
    if (completedRef.current) return false;
    const { data } = await supabase
      .from("interviews")
      .select("status")
      .eq("id", interviewId)
      .single();
    if (data?.status === "completed") {
      completedRef.current = true;
      return true;
    }
    return false;
  }, [interviewId, supabase]);

  const speakReply = useCallback(
    async (text: string) => {
      const client = clientRef.current;
      if (!client) return;
      const trimmed = text.trim();
      if (!trimmed) return;
      setPersonaCaption(trimmed);
      setStatus("speaking");
      try {
        await client.talk(trimmed);
      } catch (err) {
        console.error("Anam talk() failed", err);
      }
    },
    [],
  );

  const finishTurn = useCallback(
    async (reply: string) => {
      await speakReply(reply);
      const done = await checkCompletion();
      if (done) {
        // Allow the closing line to finish playing, then tear down.
        setTimeout(() => {
          clientRef.current?.stopStreaming().catch(() => {});
          clientRef.current = null;
          onComplete();
        }, 400);
        return;
      }
      setStatus("listening");
    },
    [speakReply, checkCompletion, onComplete],
  );

  const handleUserUtterance = useCallback(
    async (utterance: string) => {
      if (turnInFlightRef.current || completedRef.current) return;
      const text = utterance.trim();
      if (!text) return;
      turnInFlightRef.current = true;
      try {
        setStatus("thinking");
        const reply = await callBrain(text);
        await finishTurn(reply);
      } catch (err) {
        console.error(err);
        setErrorMsg(err instanceof Error ? err.message : "Something went wrong.");
        setStatus("error");
      } finally {
        turnInFlightRef.current = false;
      }
    },
    [callBrain, finishTurn],
  );

  /* ------------------------------------------------------------------ */
  /* Bootstrap: mint token, init client, wire events, start streaming.   */
  /* ------------------------------------------------------------------ */
  const start = useCallback(async () => {
    if (started) return;
    setStarted(true);
    setErrorMsg(null);
    setUserCaption("");
    setPersonaCaption("");
    setStatus("connecting");

    try {
      const personaConfig = buildPersonaConfig({ personaName, voiceId });
      const tokenRes = await fetch("/api/anam-session-token", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          token,
          personaConfig,
          sessionOptions: SESSION_OPTIONS,
        }),
      });
      if (!tokenRes.ok) {
        const body = await tokenRes.json().catch(() => ({}));
        throw new Error(body?.error ?? `Token request failed (${tokenRes.status})`);
      }
      const { sessionToken } = (await tokenRes.json()) as { sessionToken: string };

      const client = createClient(sessionToken);
      clientRef.current = client;

      // Live captions only — finalization is detected via MESSAGE_HISTORY_UPDATED.
      client.addListener(
        AnamEvent.MESSAGE_STREAM_EVENT_RECEIVED,
        (event: MessageStreamEvent) => {
          if (event.role === MessageRole.USER) {
            setUserCaption(event.content);
          } else if (event.role === MessageRole.PERSONA) {
            setPersonaCaption(event.content);
          }
        },
      );

      // Authoritative source for "a new user message was finalized".
      client.addListener(
        AnamEvent.MESSAGE_HISTORY_UPDATED,
        (messages: Message[]) => {
          if (!messages?.length) return;
          // Find the most recent user message; if its id is new, treat as a turn.
          const lastUser = [...messages].reverse().find((m) => m.role === MessageRole.USER);
          if (!lastUser?.content?.trim()) return;
          if (lastUser.id === lastUserMessageIdRef.current) return;
          lastUserMessageIdRef.current = lastUser.id;
          setUserCaption(lastUser.content);
          void handleUserUtterance(lastUser.content);
        },
      );

      client.addListener(AnamEvent.TALK_STREAM_INTERRUPTED, () => {
        setPersonaCaption("");
        if (!turnInFlightRef.current) setStatus("listening");
      });

      client.addListener(AnamEvent.MIC_PERMISSION_DENIED, () => {
        setErrorMsg(
          "Microphone access was denied. You can still type using the keyboard button.",
        );
        // Don't treat as fatal — the avatar still plays and typing works.
      });

      client.addListener(AnamEvent.CONNECTION_CLOSED, () => {
        if (!completedRef.current) setStatus("idle");
      });

      // Once the avatar's first frame plays, speak the opening line that was
      // generated upstream by the name-submission /api/chat call. This avoids
      // a second isStart:true call that would duplicate the opening in the
      // messages table.
      client.addListener(AnamEvent.VIDEO_PLAY_STARTED, () => {
        void (async () => {
          try {
            if (openingMessage?.trim()) {
              await speakReply(openingMessage);
              setStatus("listening");
            } else {
              setStatus("listening");
            }
          } catch (err) {
            console.error("Failed to speak opening line", err);
            setErrorMsg(err instanceof Error ? err.message : "Failed to start interview.");
            setStatus("error");
          }
        })();
      });

      await client.streamToVideoElement(VIDEO_ELEMENT_ID);
    } catch (err) {
      console.error(err);
      const message = err instanceof Error ? err.message : "Failed to start interview.";
      setErrorMsg(message);
      setStatus("error");
      clientRef.current = null;
      setStarted(false);
    }
  }, [started, token, personaName, voiceId, openingMessage, speakReply, handleUserUtterance]);

  /* ------------------------------------------------------------------ */
  /* Cleanup on unmount.                                                 */
  /* ------------------------------------------------------------------ */
  useEffect(() => {
    return () => {
      const client = clientRef.current;
      if (client) {
        client.stopStreaming().catch(() => {});
        clientRef.current = null;
      }
    };
  }, []);

  /* ------------------------------------------------------------------ */
  /* Typed-input path.                                                   */
  /* ------------------------------------------------------------------ */
  const submitTyped = useCallback(() => {
    const text = draft.trim();
    if (!text) return;
    setUserCaption(text);
    setDraft("");
    setTypingOpen(false);
    void handleUserUtterance(text);
  }, [draft, handleUserUtterance]);

  useEffect(() => {
    if (!typingOpen) return;
    inputRef.current?.focus();
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setTypingOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [typingOpen]);

  /* ------------------------------------------------------------------ */
  /* Render                                                              */
  /* ------------------------------------------------------------------ */
  const isLive = status === "listening" || status === "speaking" || status === "thinking";
  const statusLabel: Record<Status, string> = {
    idle: "Ready",
    connecting: "Connecting…",
    listening: "Listening",
    speaking: "Speaking",
    thinking: "Thinking…",
    error: "Error",
  };

  return (
    <div className="vi-root">
      <header className="vi-header">
        <span className={`vi-status-dot vi-status--${status}`} aria-hidden="true" />
        <span className="vi-persona-name">{personaName ?? "Interviewer"}</span>
        <span className="vi-status-label">{statusLabel[status]}</span>
      </header>

      <main className={`vi-stage vi-stage--${status}`}>
        <div className="vi-card">
          <div className="vi-card-backdrop" aria-hidden="true" />
          <video
            id={VIDEO_ELEMENT_ID}
            className="vi-video"
            autoPlay
            playsInline
          />

          {!isLive && (
            <div className="vi-overlay">
              {status === "idle" && (
                <>
                  <p className="vi-overlay-lede">
                    A short, friendly conversation. Just talk like you would
                    to a person.
                  </p>
                  <button className="vi-start" onClick={start}>
                    Start interview
                  </button>
                  <p className="vi-overlay-hint">We&apos;ll ask for your mic next.</p>
                </>
              )}
              {status === "connecting" && (
                <p className="vi-overlay-lede">Warming up the camera…</p>
              )}
              {status === "error" && (
                <>
                  <p className="vi-overlay-lede vi-overlay-error">
                    {errorMsg ?? "Something went wrong."}
                  </p>
                  <button
                    className="vi-start"
                    onClick={() => {
                      setStarted(false);
                      void start();
                    }}
                  >
                    Try again
                  </button>
                </>
              )}
            </div>
          )}
        </div>

        <div className="vi-captions" aria-live="polite">
          <p className="vi-caption-user">
            {userCaption ? (
              <>
                <span className="vi-cap-label">You</span> {userCaption}
              </>
            ) : (
              " "
            )}
          </p>
          <p className="vi-caption-persona">
            {personaCaption ? (
              <>
                <span className="vi-cap-label">{personaName ?? "Interviewer"}</span>{" "}
                {personaCaption}
              </>
            ) : (
              " "
            )}
          </p>
        </div>
      </main>

      <div className={`vi-mic-dot vi-mic-dot--${status}`} aria-hidden="true">
        <Mic size={14} strokeWidth={2.25} />
      </div>

      {isLive && !typingOpen && (
        <button
          className="vi-keyboard-toggle"
          onClick={() => setTypingOpen(true)}
          aria-label="Type instead of speaking"
          title="Type instead"
        >
          <Keyboard size={18} strokeWidth={2.25} />
        </button>
      )}

      {typingOpen && (
        <div className="vi-typing-tray" role="dialog" aria-label="Type a message">
          <input
            ref={inputRef}
            className="vi-typing-input"
            type="text"
            value={draft}
            placeholder="Type your reply…"
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                submitTyped();
              }
            }}
          />
          <button
            className="vi-typing-send"
            onClick={submitTyped}
            disabled={!draft.trim()}
            aria-label="Send"
          >
            <Send size={16} strokeWidth={2.25} />
          </button>
          <button
            className="vi-typing-close"
            onClick={() => {
              setTypingOpen(false);
              setDraft("");
            }}
            aria-label="Close text input"
          >
            <X size={16} strokeWidth={2.25} />
          </button>
        </div>
      )}
    </div>
  );
}
