-- ============================================
-- Migration 010: OST Themes
-- ============================================
-- Replaces the generic top layer of the Opportunity Solution Tree with
-- evidence-grounded "Themes". A Theme is an opportunities row with
-- type = 'theme', parented to the outcome, grouping the leaf opportunities
-- beneath it. It is generated by the Themer agent across ALL of a project's
-- interviews (cross-interview clustering), so it carries a frequency.
--
-- `type` is plain TEXT (no CHECK constraint), so no enum change is needed to
-- introduce 'theme'. We only add a metadata column to store the frequency
-- numerator/denominator that the Theme node renders ("N of M interviews").

ALTER TABLE opportunities
  ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

COMMENT ON COLUMN opportunities.metadata IS
  'Free-form metadata. For type=''theme'' nodes: { "frequency_n": <distinct interviews supporting the theme>, "frequency_m": <total interviews analyzed for the project> }.';

-- Helper: distinct-interview frequency for a theme, derived from the evidence
-- linked to the theme''s child opportunities. Used to (re)compute frequency_n
-- as new interviews are mapped. Returns 0 if the node has no children/evidence.
CREATE OR REPLACE FUNCTION theme_frequency_n(theme_id UUID)
RETURNS INT AS $$
  SELECT COUNT(DISTINCT e.interview_id)::int
  FROM opportunities child
  JOIN evidence e ON e.opportunity_id = child.id
  WHERE child.parent_id = theme_id
    AND e.interview_id IS NOT NULL;
$$ LANGUAGE sql STABLE;
